[build]
  command = "yarn run build"
  publish = "dist"
[[redirects]]
  from = "https://pickerson.com/"
  to = "https://review-mate.com/"
  status = 301
  force = false
[[redirects]]
  from = "http://pickerson.com/"
  to = "http://review-mate.com/"
  status = 301
  force = false 
[[redirects]]
  from = "https://myreviewmate.org/"
  to = "https://review-mate.com/"
  status = 301
  force = false 
[[redirects]]
  from = "http://myreviewmate.org/"
  to = "http://review-mate.com/"
  status = 301
  force = false
